///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace IOC_POC_Ranorex
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Recording1 recording.
    /// </summary>
    [TestModule("b3a0c075-b839-4f1d-bdc5-24fc6d775bb7", ModuleType.Recording, 1)]
    public partial class Recording1 : ITestModule
    {
        /// <summary>
        /// Holds an instance of the IOC_POC_RanorexRepository repository.
        /// </summary>
        public static IOC_POC_RanorexRepository repo = IOC_POC_RanorexRepository.Instance;

        static Recording1 instance = new Recording1();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Recording1()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Recording1 Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MyAccountKatalonShopAnd1MorePage.NativeViewHost' at 186;770.", repo.MyAccountKatalonShopAnd1MorePage.NativeViewHostInfo, new RecordItemIndex(0));
            repo.MyAccountKatalonShopAnd1MorePage.NativeViewHost.Click("186;770");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'customer' with focus on 'MyAccountKatalonShopAnd1MorePage'.", repo.MyAccountKatalonShopAnd1MorePage.SelfInfo, new RecordItemIndex(1));
            repo.MyAccountKatalonShopAnd1MorePage.Self.EnsureVisible();
            Keyboard.Press("customer");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MyAccountKatalonShopAnd1MorePage.NativeViewHost' at 212;872.", repo.MyAccountKatalonShopAnd1MorePage.NativeViewHostInfo, new RecordItemIndex(2));
            repo.MyAccountKatalonShopAnd1MorePage.NativeViewHost.Click("212;872");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'crz7mrb.KNG3yxv1fbn' with focus on 'MyAccountKatalonShopAnd1MorePage'.", repo.MyAccountKatalonShopAnd1MorePage.SelfInfo, new RecordItemIndex(3));
            repo.MyAccountKatalonShopAnd1MorePage.Self.PressKeys("crz7mrb.KNG3yxv1fbn");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MyAccountKatalonShopAnd1MorePage.NativeViewHost' at 289;713.", repo.MyAccountKatalonShopAnd1MorePage.NativeViewHostInfo, new RecordItemIndex(4));
            repo.MyAccountKatalonShopAnd1MorePage.NativeViewHost.Click("289;713");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MyAccountKatalonShopAnd1MorePage.NativeViewHost' at 1191;557.", repo.MyAccountKatalonShopAnd1MorePage.NativeViewHostInfo, new RecordItemIndex(5));
            repo.MyAccountKatalonShopAnd1MorePage.NativeViewHost.Click("1191;557");
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
